# Generated by Django 3.2 on 2021-04-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageModel', '0002_auto_20210426_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='img_type',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='img',
            name='name',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
