# Generated by Django 3.2 on 2021-04-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageModel', '0003_auto_20210426_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img_type',
            field=models.IntegerField(default=0),
        ),
    ]
