# Generated by Django 3.2 on 2021-04-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageModel', '0004_alter_img_img_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=20)),
                ('img', models.ImageField(upload_to='img')),
                ('img_type', models.IntegerField(default=0)),
            ],
        ),
    ]
